//! Interned index receipt generation.
//!
//! Emits a companion `*.smir.receipts.json` alongside each `*.smir.json` that
//! declares which JSON paths carry non-deterministic interned indices (`Ty`,
//! `Span`, `AllocId`, etc.).  See ADR-004 for the design rationale.
//!
//! The receipt is generated by a "spy" serde [`Serializer`] that mirrors the
//! structure of a real serializer but produces no output; it only tracks which
//! struct fields, enum variants, and array positions contain known interned
//! types. The spy runs as a separate pass before the real `serde_json`
//! serialization.

use crate::compat::serde;

use serde::ser::{self, Serialize};
use serde::Serialize as SerializeDerive;
use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::fmt;
use std::rc::Rc;

// ── Known interned type names ───────────────────────────────────────────────
//
// These are the stable_mir newtype struct names whose `#[derive(Serialize)]`
// calls `serialize_newtype_struct("<name>", &inner_usize)`.  When the spy
// serializer sees one of these names, it records the enclosing context in
// the receipt.

const INTERNED_TYPES: &[&str] = &["Ty", "Span", "AllocId", "DefId", "AdtDef", "CrateNum"];

// Interned key names that always need normalizing, regardless of whether
// the spy encounters them in a particular program's output.  These fields
// carry interned indices used as cross-reference keys by downstream tools
// (joining AggregateKind::Adt in MIR bodies with type metadata entries,
// etc.), so they can't be dropped from the output itself; they're only
// stripped for golden-file comparison.
//
// The spy may miss them because (a) the program under test doesn't
// exercise the code path that produces them, or (b) the DefId is wrapped
// in a domain-specific newtype (TraitDef, StaticDef, ClosureDef) that's
// transparent in JSON but opaque to the spy's immediate-parent check.
const SEEDED_INTERNED_KEYS: &[&str] = &["def_id", "adt_def", "ty", "span", "id", "alloc_id"];

// Interned newtype wrappers that always need normalizing.  On newer
// nightlies the serialize_index_impl! macro serializes interned types
// as bare integers, so the spy can't discover these dynamically.
const SEEDED_INTERNED_NEWTYPES: &[&str] = &["Type", "Array"];

// Interned positions that always need normalizing.
const SEEDED_INTERNED_POSITIONS: &[(&str, &[usize])] = &[
    ("Field", &[1]),
    ("Cast", &[2]),
    ("Closure", &[0]),
    ("VTable", &[0]),
    ("Adt", &[0]),
];

// ── Receipt output ──────────────────────────────────────────────────────────

/// Schema-level receipt of where interned indices appear in the JSON output.
///
/// Three categories, mapping to the three normalization patterns the jq filter
/// needs (see ADR-004 for the full mapping table).
#[derive(Debug, Clone, SerializeDerive)]
pub struct Receipts {
    /// Object field names whose values are interned indices.
    pub interned_keys: BTreeSet<String>,
    /// Enum variant / newtype names that wrap a bare interned integer.
    pub interned_newtypes: BTreeSet<String>,
    /// Parent array name → positions within the array carrying interned indices.
    pub interned_positions: BTreeMap<String, BTreeSet<usize>>,
}

// ── Tracker (mutable state) ─────────────────────────────────────────────────

/// What kind of container we're currently inside.
#[derive(Debug, Clone)]
#[allow(dead_code)] // SeqElement's index is structurally meaningful even if unused in matching
enum ParentKind {
    /// Serializing the value for a struct/map field with this key.
    Field(String),
    /// Serializing element N of a tuple variant / tuple struct with this name.
    TupleEntry(String, usize),
    /// Serializing the inner value of a newtype variant / newtype struct.
    Newtype(String),
    /// Serializing element N of a plain sequence (no named parent).
    SeqElement(usize),
    /// Top-level or unknown context.
    Root,
}

#[derive(Debug)]
struct Tracker {
    /// Stack of enclosing contexts.  The spy pushes on entry and pops on exit.
    context: Vec<ParentKind>,
    /// The set of type names we recognize as interned.
    interned_names: HashSet<&'static str>,
    // Accumulated receipt data:
    keys: BTreeSet<String>,
    newtypes: BTreeSet<String>,
    positions: BTreeMap<String, BTreeSet<usize>>,
}

impl Tracker {
    fn new() -> Self {
        let mut positions = BTreeMap::new();
        for (name, idxs) in SEEDED_INTERNED_POSITIONS {
            positions
                .entry(name.to_string())
                .or_insert_with(BTreeSet::new)
                .extend(idxs.iter().copied());
        }
        Self {
            context: vec![ParentKind::Root],
            interned_names: INTERNED_TYPES.iter().copied().collect(),
            keys: SEEDED_INTERNED_KEYS.iter().map(|s| s.to_string()).collect(),
            newtypes: SEEDED_INTERNED_NEWTYPES
                .iter()
                .map(|s| s.to_string())
                .collect(),
            positions,
        }
    }

    /// Called when `serialize_newtype_struct` sees a known interned type.
    ///
    /// Looks at the immediate parent context to classify the finding.
    /// Only struct fields, newtype wrappers, and tuple positions are
    /// recorded; sequence elements and the root context are ignored
    /// (the interned value is inside a collection, not directly
    /// assignable to a named field).
    fn record_interned(&mut self) {
        let Some(frame) = self.context.last() else {
            return;
        };
        match frame {
            ParentKind::Field(key) => {
                self.keys.insert(key.clone());
            }
            ParentKind::Newtype(name) => {
                self.newtypes.insert(name.clone());
            }
            ParentKind::TupleEntry(name, idx) => {
                self.positions.entry(name.clone()).or_default().insert(*idx);
            }
            ParentKind::SeqElement(_) | ParentKind::Root => {
                // Inside a sequence or at top level; the enclosing field
                // is a collection, not a direct interned-index carrier.
            }
        }
    }

    fn into_receipts(self) -> Receipts {
        Receipts {
            interned_keys: self.keys,
            interned_newtypes: self.newtypes,
            interned_positions: self.positions,
        }
    }
}

type SharedTracker = Rc<RefCell<Tracker>>;

// ── Error type ──────────────────────────────────────────────────────────────

/// The spy serializer never truly fails; this error type exists only to satisfy
/// serde's trait bounds.
#[derive(Debug)]
struct SpyError;

impl fmt::Display for SpyError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("spy serializer error (should never happen)")
    }
}

impl std::error::Error for SpyError {}

impl ser::Error for SpyError {
    fn custom<T: fmt::Display>(_msg: T) -> Self {
        SpyError
    }
}

// ── Spy serializer ──────────────────────────────────────────────────────────

struct SpySerializer {
    tracker: SharedTracker,
}

impl SpySerializer {
    fn new(tracker: SharedTracker) -> Self {
        Self { tracker }
    }
}

/// Compound serializer for sequences, tuples, structs, and maps.
///
/// A single type handles all compound serde traits.  The `parent` field
/// records the context that was pushed when the compound was opened;
/// `index` tracks the current element position for tuple/seq types.
struct SpyCompound {
    tracker: SharedTracker,
    /// Name of the enclosing construct (struct name, variant name, etc.)
    name: String,
    /// Current element index (for tuples and sequences).
    index: usize,
    /// Whether this is a struct-like compound (named fields) vs. tuple-like.
    #[allow(dead_code)] // reserved for potential future use in context classification
    is_struct: bool,
}

impl SpyCompound {
    fn new(tracker: SharedTracker, name: &str, is_struct: bool) -> Self {
        Self {
            tracker,
            name: name.to_string(),
            index: 0,
            is_struct,
        }
    }
}

// ── Serializer trait impl ───────────────────────────────────────────────────

macro_rules! spy_primitive {
    ($method:ident, $ty:ty) => {
        fn $method(self, _v: $ty) -> Result<Self::Ok, Self::Error> {
            Ok(())
        }
    };
}

impl ser::Serializer for SpySerializer {
    type Ok = ();
    type Error = SpyError;
    type SerializeSeq = SpyCompound;
    type SerializeTuple = SpyCompound;
    type SerializeTupleStruct = SpyCompound;
    type SerializeTupleVariant = SpyCompound;
    type SerializeMap = SpyCompound;
    type SerializeStruct = SpyCompound;
    type SerializeStructVariant = SpyCompound;

    spy_primitive!(serialize_bool, bool);
    spy_primitive!(serialize_i8, i8);
    spy_primitive!(serialize_i16, i16);
    spy_primitive!(serialize_i32, i32);
    spy_primitive!(serialize_i64, i64);
    spy_primitive!(serialize_u8, u8);
    spy_primitive!(serialize_u16, u16);
    spy_primitive!(serialize_u32, u32);
    spy_primitive!(serialize_u64, u64);
    spy_primitive!(serialize_f32, f32);
    spy_primitive!(serialize_f64, f64);
    spy_primitive!(serialize_char, char);
    spy_primitive!(serialize_str, &str);
    spy_primitive!(serialize_bytes, &[u8]);

    fn serialize_none(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }

    fn serialize_some<T: ?Sized + Serialize>(self, value: &T) -> Result<Self::Ok, Self::Error> {
        value.serialize(SpySerializer::new(self.tracker))
    }

    fn serialize_unit(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }

    fn serialize_unit_struct(self, _name: &'static str) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }

    fn serialize_unit_variant(
        self,
        _name: &'static str,
        _variant_index: u32,
        _variant: &'static str,
    ) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }

    fn serialize_newtype_struct<T: ?Sized + Serialize>(
        self,
        name: &'static str,
        value: &T,
    ) -> Result<Self::Ok, Self::Error> {
        {
            let tracker = self.tracker.borrow();
            if tracker.interned_names.contains(name) {
                drop(tracker);
                self.tracker.borrow_mut().record_interned();
                return Ok(());
            }
        }
        // Not an interned type; push context and recurse.
        self.tracker
            .borrow_mut()
            .context
            .push(ParentKind::Newtype(name.to_string()));
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        result
    }

    fn serialize_newtype_variant<T: ?Sized + Serialize>(
        self,
        _name: &'static str,
        _variant_index: u32,
        variant: &'static str,
        value: &T,
    ) -> Result<Self::Ok, Self::Error> {
        self.tracker
            .borrow_mut()
            .context
            .push(ParentKind::Newtype(variant.to_string()));
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        result
    }

    fn serialize_seq(self, _len: Option<usize>) -> Result<Self::SerializeSeq, Self::Error> {
        Ok(SpyCompound::new(self.tracker, "", false))
    }

    fn serialize_tuple(self, _len: usize) -> Result<Self::SerializeTuple, Self::Error> {
        Ok(SpyCompound::new(self.tracker, "", false))
    }

    fn serialize_tuple_struct(
        self,
        name: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeTupleStruct, Self::Error> {
        // On newer nightlies (post-ThreadLocalIndex), interned types like
        // Ty(usize, ThreadLocalIndex) serialize as tuple structs instead of
        // newtype structs.  Detect them the same way we detect newtypes.
        {
            let tracker = self.tracker.borrow();
            if tracker.interned_names.contains(name) {
                drop(tracker);
                self.tracker.borrow_mut().record_interned();
                // Return a compound that ignores its fields; we've already
                // recorded the finding and don't need to recurse deeper.
                return Ok(SpyCompound::new(self.tracker, "", false));
            }
        }
        Ok(SpyCompound::new(self.tracker, name, false))
    }

    fn serialize_tuple_variant(
        self,
        _name: &'static str,
        _variant_index: u32,
        variant: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeTupleVariant, Self::Error> {
        Ok(SpyCompound::new(self.tracker, variant, false))
    }

    fn serialize_map(self, _len: Option<usize>) -> Result<Self::SerializeMap, Self::Error> {
        Ok(SpyCompound::new(self.tracker, "", true))
    }

    fn serialize_struct(
        self,
        _name: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeStruct, Self::Error> {
        Ok(SpyCompound::new(self.tracker, "", true))
    }

    fn serialize_struct_variant(
        self,
        _name: &'static str,
        _variant_index: u32,
        variant: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeStructVariant, Self::Error> {
        Ok(SpyCompound::new(self.tracker, variant, true))
    }
}

// ── Compound trait impls ────────────────────────────────────────────────────

impl ser::SerializeSeq for SpyCompound {
    type Ok = ();
    type Error = SpyError;

    fn serialize_element<T: ?Sized + Serialize>(&mut self, value: &T) -> Result<(), Self::Error> {
        self.tracker
            .borrow_mut()
            .context
            .push(ParentKind::SeqElement(self.index));
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        self.index += 1;
        result
    }

    fn end(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }
}

impl ser::SerializeTuple for SpyCompound {
    type Ok = ();
    type Error = SpyError;

    fn serialize_element<T: ?Sized + Serialize>(&mut self, value: &T) -> Result<(), Self::Error> {
        let parent = if self.name.is_empty() {
            ParentKind::SeqElement(self.index)
        } else {
            ParentKind::TupleEntry(self.name.clone(), self.index)
        };
        self.tracker.borrow_mut().context.push(parent);
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        self.index += 1;
        result
    }

    fn end(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }
}

impl ser::SerializeTupleStruct for SpyCompound {
    type Ok = ();
    type Error = SpyError;

    fn serialize_field<T: ?Sized + Serialize>(&mut self, value: &T) -> Result<(), Self::Error> {
        let parent = if self.name.is_empty() {
            ParentKind::SeqElement(self.index)
        } else {
            ParentKind::TupleEntry(self.name.clone(), self.index)
        };
        self.tracker.borrow_mut().context.push(parent);
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        self.index += 1;
        result
    }

    fn end(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }
}

impl ser::SerializeTupleVariant for SpyCompound {
    type Ok = ();
    type Error = SpyError;

    fn serialize_field<T: ?Sized + Serialize>(&mut self, value: &T) -> Result<(), Self::Error> {
        self.tracker
            .borrow_mut()
            .context
            .push(ParentKind::TupleEntry(self.name.clone(), self.index));
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        self.index += 1;
        result
    }

    fn end(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }
}

impl ser::SerializeMap for SpyCompound {
    type Ok = ();
    type Error = SpyError;

    fn serialize_key<T: ?Sized + Serialize>(&mut self, _key: &T) -> Result<(), Self::Error> {
        // We don't track map keys for now; they'd need to be captured as
        // strings for the Field context, which requires serializing the key
        // to a string.  For SmirJson's purposes, all maps are HashMap<K,V>
        // and the keys aren't interned indices themselves.
        Ok(())
    }

    fn serialize_value<T: ?Sized + Serialize>(&mut self, value: &T) -> Result<(), Self::Error> {
        value.serialize(SpySerializer::new(self.tracker.clone()))
    }

    fn end(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }
}

impl ser::SerializeStruct for SpyCompound {
    type Ok = ();
    type Error = SpyError;

    fn serialize_field<T: ?Sized + Serialize>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), Self::Error> {
        self.tracker
            .borrow_mut()
            .context
            .push(ParentKind::Field(key.to_string()));
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        result
    }

    fn end(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }
}

impl ser::SerializeStructVariant for SpyCompound {
    type Ok = ();
    type Error = SpyError;

    fn serialize_field<T: ?Sized + Serialize>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), Self::Error> {
        self.tracker
            .borrow_mut()
            .context
            .push(ParentKind::Field(key.to_string()));
        let result = value.serialize(SpySerializer::new(self.tracker.clone()));
        self.tracker.borrow_mut().context.pop();
        result
    }

    fn end(self) -> Result<Self::Ok, Self::Error> {
        Ok(())
    }
}

// ── Public API ──────────────────────────────────────────────────────────────

/// Serialize `value` through the spy serializer to discover which JSON paths
/// carry interned indices.  Returns a [`Receipts`] describing the findings.
pub fn collect_receipts<T: Serialize>(value: &T) -> Receipts {
    let tracker = Rc::new(RefCell::new(Tracker::new()));
    // The spy serializer never fails (SpyError is unreachable in practice),
    // but we handle it gracefully just in case.
    let _ = value.serialize(SpySerializer::new(tracker.clone()));
    let tracker = Rc::try_unwrap(tracker)
        .expect("tracker should have a single owner after serialization")
        .into_inner();
    tracker.into_receipts()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal stand-in for a newtype that mimics stable_mir's Ty(usize).
    #[derive(serde::Serialize)]
    struct Ty(usize);

    /// Minimal stand-in for Span(usize).
    #[derive(serde::Serialize)]
    struct Span(usize);

    /// Minimal stand-in for AllocId(usize).
    #[derive(serde::Serialize)]
    struct AllocId(usize);

    /// An enum variant wrapping Ty, like stable_mir's GenericArgKind::Type.
    #[derive(serde::Serialize)]
    enum GenArg {
        Type(Ty),
        Const(u64),
    }

    /// A tuple variant carrying a Ty at a known position, like Cast or Closure.
    #[derive(serde::Serialize)]
    enum Rvalue {
        Cast(String, String, Ty),
        Use(String),
    }

    /// A struct with named fields containing interned types.
    #[derive(serde::Serialize)]
    struct Statement {
        kind: String,
        span: Span,
    }

    #[derive(serde::Serialize)]
    struct TestRoot {
        items: Vec<Statement>,
        args: Vec<GenArg>,
        rvalues: Vec<Rvalue>,
        alloc_id: AllocId,
    }

    #[test]
    fn discovers_interned_keys() {
        let root = TestRoot {
            items: vec![Statement {
                kind: "Assign".into(),
                span: Span(42),
            }],
            args: vec![GenArg::Type(Ty(7)), GenArg::Const(99)],
            rvalues: vec![
                Rvalue::Cast("Unsize".into(), "op".into(), Ty(13)),
                Rvalue::Use("x".into()),
            ],
            alloc_id: AllocId(5),
        };

        let receipts = collect_receipts(&root);

        // "span" should be in interned_keys (struct field)
        assert!(
            receipts.interned_keys.contains("span"),
            "expected 'span' in interned_keys, got: {:?}",
            receipts.interned_keys
        );

        // "alloc_id" should be in interned_keys (struct field)
        assert!(
            receipts.interned_keys.contains("alloc_id"),
            "expected 'alloc_id' in interned_keys, got: {:?}",
            receipts.interned_keys
        );

        // "Type" should be in interned_newtypes (enum newtype variant)
        assert!(
            receipts.interned_newtypes.contains("Type"),
            "expected 'Type' in interned_newtypes, got: {:?}",
            receipts.interned_newtypes
        );

        // Cast[2] should be in interned_positions
        assert!(
            receipts
                .interned_positions
                .get("Cast")
                .map_or(false, |s| s.contains(&2)),
            "expected Cast[2] in interned_positions, got: {:?}",
            receipts.interned_positions
        );

        // Seeded values should always be present, even if the test type
        // doesn't exercise the code paths that produce them.
        for key in SEEDED_INTERNED_KEYS {
            assert!(
                receipts.interned_keys.contains(*key),
                "expected seeded key '{}' in interned_keys, got: {:?}",
                key,
                receipts.interned_keys
            );
        }
        for nt in SEEDED_INTERNED_NEWTYPES {
            assert!(
                receipts.interned_newtypes.contains(*nt),
                "expected seeded newtype '{}' in interned_newtypes, got: {:?}",
                nt,
                receipts.interned_newtypes
            );
        }
        for (name, idxs) in SEEDED_INTERNED_POSITIONS {
            for idx in *idxs {
                assert!(
                    receipts
                        .interned_positions
                        .get(*name)
                        .map_or(false, |s| s.contains(idx)),
                    "expected seeded position {}[{}] in interned_positions, got: {:?}",
                    name,
                    idx,
                    receipts.interned_positions
                );
            }
        }
    }
}
