#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: run_ui_tests.sh [--verbose] [--save-generated-output] [--save-debug-output] RUST_DIR

Options:
  --verbose                Print passing and skipped tests.
  --save-generated-output   Do not delete generated *.smir.json files.
  --save-debug-output      On failure, print stderr snippet inline and save
                           full stderr to <UI_DIR>/debug/<test_name>.stderr.
  --help, -h               Show this help.

Environment:
  RUN_SMIR                 Optional override for the runner command.
                           Example: RUN_SMIR=./target/debug/stable_mir_json
                           (If you include flags, they will be split on spaces.)
EOF
}

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '%s\n' "$*"
}

# -------------------------
# Arg parsing
# -------------------------
VERBOSE=0
SAVE_GENERATED_OUTPUT=0
SAVE_DEBUG_OUTPUT=0
RUST_DIR=""

while (( $# > 0 )); do
  case "$1" in
    --verbose)
      VERBOSE=1
      shift
      ;;
    --save-generated-output)
      SAVE_GENERATED_OUTPUT=1
      shift
      ;;
    --save-debug-output)
      SAVE_DEBUG_OUTPUT=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --*)
      die "unknown option: $1"
      ;;
    *)
      if [[ -z "$RUST_DIR" ]]; then
        RUST_DIR=$1
      else
        die "unexpected argument: $1"
      fi
      shift
      ;;
  esac
done

[[ -n "$RUST_DIR" ]] || { usage; exit 1; }
[[ -d "$RUST_DIR" ]] || die "RUST_DIR is not a directory: $RUST_DIR"

# -------------------------
# Paths
# -------------------------
UI_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# parse_test_directives.awk handles both skip-detection and flag extraction
# in a single pass over each test file. It prints one line:
#   SKIP<TAB>reason     if the test should not run on this host
#   FLAGS<TAB>flags     if the test should run (flags may be empty)
AWK_SCRIPT="${UI_DIR}/parse_test_directives.awk"

# Ensure the rust checkout is at the expected commit (handles bare repos)
source "$UI_DIR/ensure_rustc_commit.sh"
# Determine the active nightly and use per-nightly effective lists if available.
# The nightly channel name (e.g., nightly-2025-03-01) is derived from the
# active toolchain; override directories are generated by diff_test_lists.sh.
ACTIVE_NIGHTLY=$(rustup show active-toolchain 2>/dev/null \
  | grep -oE 'nightly-[0-9]{4}-[0-9]{2}-[0-9]{2}' || true)
OVERRIDE_DIR="${UI_DIR}/overrides/${ACTIVE_NIGHTLY}"

if [[ -n "$ACTIVE_NIGHTLY" && -f "${OVERRIDE_DIR}/passing.tsv" ]]; then
  PASSING_TSV="${OVERRIDE_DIR}/passing.tsv"
  if [[ ! -s "$PASSING_TSV" ]]; then
    die "Override passing.tsv for ${ACTIVE_NIGHTLY} is empty; regenerate with: bash tests/ui/diff_test_lists.sh --emit RUST_DIR ${ACTIVE_NIGHTLY}"
  fi
  log "Using effective test list for ${ACTIVE_NIGHTLY}"
elif [[ -n "$ACTIVE_NIGHTLY" ]]; then
  log "WARNING: no UI test override for ${ACTIVE_NIGHTLY}; falling back to base list (results may be unreliable)"
  PASSING_TSV="${UI_DIR}/passing.tsv"
else
  PASSING_TSV="${UI_DIR}/passing.tsv"
fi
[[ -f "$PASSING_TSV" ]] || die "Missing TSV file: $PASSING_TSV"

DEBUG_DIR="${UI_DIR}/debug"
if (( SAVE_DEBUG_OUTPUT )); then
  rm -rf "$DEBUG_DIR"
  mkdir -p "$DEBUG_DIR"
fi

# Collect failed test paths for easy re-investigation.
FAILED_FILE=$(mktemp /tmp/ui_failed.XXXXXX)
trap 'rm -f "$FAILED_FILE"' EXIT

# -------------------------
# Runner setup
# -------------------------
declare -a RUN_SMIR_CMD

if [[ -z "${RUN_SMIR:-}" ]]; then
  # Build once upfront, then invoke the binary directly to avoid cargo's
  # per-invocation freshness check (~2-3s overhead * thousands of tests).
  log "RUN_SMIR unset; building and using binary directly"
  cargo build

  SMIR_BIN="./target/debug/stable_mir_json"
  [[ -x "$SMIR_BIN" ]] || die "failed to build: $SMIR_BIN"

  SYSROOT_LIB="$(rustc --print sysroot)/lib"
  DYLD_LIBRARY_PATH="${SYSROOT_LIB}${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
  LD_LIBRARY_PATH="${SYSROOT_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
  export DYLD_LIBRARY_PATH LD_LIBRARY_PATH

  RUN_SMIR_CMD=( "$SMIR_BIN" -Zno-codegen )
else
  # Allow RUN_SMIR to be either a path or a simple "path flags..." string.
  # Note: this splits on spaces (no shell quoting).
  read -r -a RUN_SMIR_CMD <<<"$RUN_SMIR"
  [[ -n "${RUN_SMIR_CMD[0]:-}" ]] || die "RUN_SMIR is set but empty"
  [[ -x "${RUN_SMIR_CMD[0]}" ]] || die "RUN_SMIR binary is not executable: ${RUN_SMIR_CMD[0]}"
  RUN_SMIR_CMD+=( -Zno-codegen )
fi

# -------------------------
# Host detection
# -------------------------

# Normalize host arch: uname -m reports "arm64" on macOS, but rustc
# test directives use "aarch64".
HOST_UNAME_ARCH="$(uname -m)"
case "$HOST_UNAME_ARCH" in
  arm64)   HOST_ARCH="aarch64" ;;
  *)       HOST_ARCH="$HOST_UNAME_ARCH" ;;
esac

# Normalize host OS to match rustc directive conventions.
HOST_UNAME_OS="$(uname -s)"
case "$HOST_UNAME_OS" in
  Linux)   HOST_OS="linux" ;;
  Darwin)  HOST_OS="macos" ;;
  MINGW*|MSYS*|CYGWIN*) HOST_OS="windows" ;;
  FreeBSD) HOST_OS="freebsd" ;;
  *)       HOST_OS="$(echo "$HOST_UNAME_OS" | tr '[:upper:]' '[:lower:]')" ;;
esac

# Pointer width for only-32bit / only-64bit directives.
HOST_BITS="$(getconf LONG_BIT 2>/dev/null || echo 64)"

# Path-based arch filter: skip tests whose path contains a foreign arch
# directory (e.g., tests/ui/asm/x86_64/ on aarch64).
FOREIGN_ARCH_RE=""
case "$HOST_ARCH" in
  aarch64) FOREIGN_ARCH_RE='/(x86_64|x86|i686|i386|s390x|powerpc|mips|riscv|loongarch|sparc|hexagon|bpf|avr|msp430|nvptx)/' ;;
  x86_64)  FOREIGN_ARCH_RE='/(aarch64|arm|s390x|powerpc|mips|riscv|loongarch|sparc|hexagon|bpf|avr|msp430|nvptx)/' ;;
esac

log "Running regression tests for passing UI cases (host: $HOST_ARCH, os: $HOST_OS)..."

start_time=$SECONDS
failed=0
passed=0
skipped=0
total=0

while IFS= read -r test; do
  [[ -n "$test" ]] || continue

  test_path="${RUST_SRC_DIR}/${test}"
  test_name="$(basename "$test" .rs)"
  json_file="${PWD}/${test_name}.smir.json"

  (( ++total ))

  # --- Skip check and flag extraction ---
  # Fast path: skip tests whose path contains a foreign-arch directory name
  # (avoids reading the file at all).
  if [[ -n "$FOREIGN_ARCH_RE" ]] && grep -qE "$FOREIGN_ARCH_RE" <<<"$test"; then
    (( ++skipped ))
    (( VERBOSE )) && log "SKIPPED (arch path): $test_path"
    continue
  fi

  # Parse //@ directives: determines whether to skip (and why) and
  # extracts compile-flags/edition/rustc-env in one pass.
  directive_result=$(awk -v host_os="$HOST_OS" \
                         -v host_arch="$HOST_ARCH" \
                         -v host_bits="$HOST_BITS" \
                         -f "$AWK_SCRIPT" "$test_path" 2>/dev/null || echo "FLAGS	")

  directive_kind="${directive_result%%	*}"
  directive_value="${directive_result#*	}"

  if [[ "$directive_kind" == "SKIP" ]]; then
    (( ++skipped ))
    (( VERBOSE )) && log "SKIPPED ($directive_value): $test_path"
    continue
  fi

  test_flags="$directive_value"

  # shellcheck disable=SC2086 # intentional word-splitting of $test_flags
  if (( SAVE_DEBUG_OUTPUT )); then
    test_stderr=$(mktemp)
    "${RUN_SMIR_CMD[@]}" ${test_flags} "$test_path" >/dev/null 2>"$test_stderr" && rc=0 || rc=$?
  else
    "${RUN_SMIR_CMD[@]}" ${test_flags} "$test_path" >/dev/null 2>&1 && rc=0 || rc=$?
  fi

  if (( rc == 0 )); then
    (( ++passed ))
    if (( VERBOSE )); then
      log "✅ PASSING: $test_path"
    fi
  else
    log "❌ FAILED: $test_path (exit $rc)"
    printf '%s\t%d\n' "$test" "$rc" >> "$FAILED_FILE"
    if (( SAVE_DEBUG_OUTPUT )) && [[ -s "$test_stderr" ]]; then
      tail -4 "$test_stderr" | sed 's/^/   /'
      cp -- "$test_stderr" "${DEBUG_DIR}/${test_name}.stderr"
    fi
    (( ++failed ))
  fi
  (( SAVE_DEBUG_OUTPUT )) && rm -f -- "$test_stderr"

  # Clean up generated JSON
  if (( ! SAVE_GENERATED_OUTPUT )) && [[ -f "$json_file" ]]; then
    rm -f -- "$json_file"
  fi
done <"$PASSING_TSV"

elapsed=$(( SECONDS - start_time ))
printf '—— Summary ——\n'
printf 'Total tests : %d\n' "$total"
printf 'Skipped     : %d\n' "$skipped"
printf 'Passed      : %d\n' "$passed"
printf 'Failed      : %d\n' "$failed"
printf 'Elapsed     : %dm%02ds\n' $(( elapsed / 60 )) $(( elapsed % 60 ))

run=$(( total - skipped ))
if (( run > 0 )); then
  ratio_passed="$(awk "BEGIN { printf \"%.2f\", $passed/$run }")"
  ratio_failed="$(awk "BEGIN { printf \"%.2f\", $failed/$run }")"
  printf '\nPassing ratio : %s\nFailing ratio : %s\n' "$ratio_passed" "$ratio_failed"
fi

if (( failed > 0 )); then
  printf '\nFailed tests:\n'
  while IFS=$'\t' read -r fpath frc; do
    printf '  %s (exit %s)\n' "$fpath" "$frc"
  done < "$FAILED_FILE"
fi

if (( SAVE_DEBUG_OUTPUT && failed > 0 )); then
  printf '\nDebug output saved to: %s\n' "$DEBUG_DIR"
fi

(( failed == 0 )) || exit 1
